name: Build APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar
        uses: actions/checkout@v4

      - name: Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Crear Gradle
        run: |
          wget -q https://services.gradle.org/distributions/gradle-8.0-bin.zip
          unzip -q gradle-8.0-bin.zip
          ./gradle-8.0/bin/gradle wrapper --gradle-version 8.0
          chmod +x gradlew

      - name: Compilar
        run: ./gradlew assembleDebug

      - name: Subir APK
        uses: actions/upload-artifact@v4
        with:
          name: MiApkFinal
          path: app/build/outputs/apk/debug/app-debug.apk
